apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sql-data-policy
  namespace: m2cloud
spec:
  podSelector:
    matchLabels:
      app: sql-data
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: applicants-api
        - podSelector:
            matchLabels:
              app: jobs-api
        - podSelector:
            matchLabels:
              app: identity-api
      ports:
        - protocol: TCP
          port: 1433
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-policy
  namespace: m2cloud
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: applicants-api
        - podSelector:
            matchLabels:
              app: jobs-api
      ports:
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 15672
