apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: m2cloud
type: Opaque
stringData:
  SA_PASSWORD: "YourStrong@Passw0rd"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  JWT_SECRET: "your-super-secret-jwt-key-here-min-32-chars"
