apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: m2cloud-ingress
  namespace: m2cloud
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - m2cloud.local
        - api.m2cloud.local
      secretName: tls-secret
  rules:
    - host: m2cloud.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
    - host: api.m2cloud.local
      http:
        paths:
          - path: /applicants
            pathType: Prefix
            backend:
              service:
                name: applicants-api-service
                port:
                  number: 80
          - path: /jobs
            pathType: Prefix
            backend:
              service:
                name: jobs-api-service
                port:
                  number: 80
          - path: /identity
            pathType: Prefix
            backend:
              service:
                name: identity-api-service
                port:
                  number: 80
