apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-api
  template:
    metadata:
      labels:
        app: jobs-api
    spec:
      containers:
      - name: jobs-api
        image: warshall/jobs-api:v1.0.0
        env:
        - name: ApiSettings__ConnectionString
          value: "Server=sql-data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;"
        - name: ApiSettings__RedisConnectionString
          value: "redis:6379"
        - name: RabbitMq__Host
          value: "rabbitmq"
        - name: ApiSettings__HostRabbitmq
          value: "rabbitmq"
        - name: ASPNETCORE_URLS
          value: "Development"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jobs-api
  namespace: projet-apps
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: jobs-api
