{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc
  namespace: {{ .Values.namespaces.apps | default "projet-apps" }}
  labels:
    app: webmvc
spec:
  replicas: {{ .Values.web.replicas | default 1 }}
  selector:
    matchLabels:
      app: webmvc
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      {{- if .Values.web.affinity.enabled }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - jobs-api
                        - applicants-api
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
        - name: webmvc
          image: "{{ .Values.images.web.repository | default "warshall/webmvc" }}:{{ .Values.images.web.tag | default "v1.0.0" }}"
          imagePullPolicy: {{ .Values.images.pullPolicy | default "Always" }}
          env:
            - name: ApiSettings__IdentityApiUrl
              value: {{ .Values.web.env.identityApiUrl | quote }}
            - name: ApiSettings__JobsApiUrl
              value: {{ .Values.web.env.jobsApiUrl | quote }}
            - name: ApiSettings__ApplicantsApiUrl
              value: {{ .Values.web.env.applicantsApiUrl | quote }}
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.web.env.environment | default "Development" | quote }}
          ports:
            - containerPort: {{ .Values.web.containerPort | default 80 }}

          resources:
            requests:
              cpu: {{ .Values.web.resources.requests.cpu | default "100m" | quote }}
              memory: {{ .Values.web.resources.requests.memory | default "900Mi" | quote }}
            limits:
              cpu: {{ .Values.web.resources.limits.cpu | default "1" | quote }}
              memory: {{ .Values.web.resources.limits.memory | default "2000Mi" | quote }}

          livenessProbe:
            httpGet:
              path: {{ .Values.web.livenessProbe.path | default "/" | quote }}
              port: {{ .Values.web.containerPort | default 80 }}
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds | default 60 }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds | default 10 }}
{{- end }}
