{{- if and .Values.web.enabled .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webmvc-ingress
  namespace: {{ .Values.namespaces.apps | default "projet-apps" }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.web.ingress.className | default "nginx" | quote }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.web.ingress.sslRedirect | default "true" | quote }}
spec:
  ingressClassName: {{ .Values.web.ingress.className | default "nginx" }}
  tls:
    - hosts:
        - {{ .Values.web.ingress.host | default "localhost" | quote }}
      secretName: {{ .Values.web.ingress.tlsSecretName | default "webmvc-tls" | quote }}
  rules:
    - host: {{ .Values.web.ingress.host | default "localhost" | quote }}
      http:
        paths:
          - path: {{ .Values.web.ingress.path | default "/" | quote }}
            pathType: {{ .Values.web.ingress.pathType | default "Prefix" | quote }}
            backend:
              service:
                name: webmvc
                port:
                  number: {{ .Values.web.service.port | default 80 }}
{{- end }}
