apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: m2cloud
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  SQL_SERVER: "sql-data-service"
  SQL_DATABASE: "M2CloudDB"
  IDENTITY_API_URL: "http://identity-api-service:80"
  APPLICANTS_API_URL: "http://applicants-api-service:80"
  JOBS_API_URL: "http://jobs-api-service:80"
