{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "m2cloud.fullname" . }}-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  labels:
    {{- include "m2cloud.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.web }}
        - {{ .Values.ingress.hosts.api }}
      secretName: {{ .Values.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.web }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
    - host: {{ .Values.ingress.hosts.api }}
      http:
        paths:
          - path: /applicants
            pathType: Prefix
            backend:
              service:
                name: applicants-api-service
                port:
                  number: 80
          - path: /jobs
            pathType: Prefix
            backend:
              service:
                name: jobs-api-service
                port:
                  number: 80
          - path: /identity
            pathType: Prefix
            backend:
              service:
                name: identity-api-service
                port:
                  number: 80
{{- end }}
