apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "m2cloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  SA_PASSWORD: {{ .Values.sqlData.secrets.saPassword | quote }}
  RABBITMQ_USER: {{ .Values.rabbitmq.secrets.user | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.secrets.password | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
