{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "m2cloud.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "m2cloud.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "m2cloud.fullname" . }}-role
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "m2cloud.fullname" . }}-rolebinding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "m2cloud.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: {{ include "m2cloud.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
