apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmvc
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      # --- AJOUT DES AFFINITÉS ---
      # Le Web doit être proche des APIs Jobs et Applicants
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jobs-api
                  - applicants-api
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: webmvc
        image: warshall/webmvc:v1.0.0
        env:
        - name: IdentityUrl
          value: "http://identity-api.projet-apps.svc.cluster.local"
        - name: ApplicantsUrl
          value: "http://applicants-api.projet-apps.svc.cluster.local"
        - name: JobsUrl
          value: "http://jobs-api.projet-apps.svc.cluster.local"
        # - name: IdentityUrl
        #   value: "http://identity-api"
        # - name: ApplicantsUrl
        #   value: "http://applicants-api"
        # - name: JobsUrl
        #   value: "http://jobs-api"
        ports:
        - containerPort: 80
        # --- AJOUT DES LIMITES DE PERF ---
        resources:
          requests:
            cpu: "4m"
            memory: "900Mi"
          limits:
            cpu: "1"
            memory: "2000Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: webmvc
  namespace: projet-apps
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webmvc
