apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: projet-apps
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Projet Architecture - Daniel</title>
        <style>
            body { font-family: 'Segoe UI', sans-serif; background: #121212; color: white; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
            .card { background: #1e1e1e; padding: 2rem; border-radius: 15px; box-shadow: 0 10px 30px rgba(0,0,0,0.5); text-align: center; border: 1px solid #333; }
            h1 { color: #00e676; margin-bottom: 0.5rem; }
            p { color: #aaa; }
            .status { display: inline-block; padding: 5px 15px; background: #00e67622; color: #00e676; border-radius: 20px; font-size: 0.8rem; border: 1px solid #00e676; }
        </style>
    </head>
    <body>
        <div class="card">
            <h1>Architecture Microservices</h1>
            <p>Déploiement Kubernetes de Daniel</p>
            <div class="status">● Stack ELK & APIs Opérationnelles</div>
        </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmvc
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["jobs-api", "applicants-api"]
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: webmvc
        image: nginx:alpine
        imagePullPolicy: Always
        env:
        - name: LOGSTASH_URL
          value: "logstash:5044"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "4m"
            memory: "900Mi"
          limits:
            cpu: "1000m"
            memory: "2000Mi"
        # --- INJECTION DU SITE VITRINE ---
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        # ---------------------------------
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
      volumes:
      - name: html-volume
        configMap:
          name: web-content
---
apiVersion: v1
kind: Service
metadata:
  name: webmvc
  namespace: projet-apps
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webmvc