apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc
  namespace: projet-apps
spec:
  replicas: 1 # Sera géré par le HPA plus tard
  selector:
    matchLabels:
      app: webmvc
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      # --- AFFINITÉ (Web proche de Jobs et Applicants) ---
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["jobs-api", "applicants-api"]
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: webmvc
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # --- RESSOURCES (Strictement imposées par le sujet) ---
        resources:
          requests:
            cpu: "4m"
            memory: "900Mi"
          limits:
            cpu: "1000m"
            memory: "2000Mi"
        # --- SONDES DE SANTÉ ---
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: webmvc
  namespace: projet-apps
spec:
  type: ClusterIP # Sera exposé via l'Ingress (Rôle 3)
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webmvc