apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc
  namespace: projet-apps
spec:
  # Note : replicas sera géré par le HPA (min 2)
  selector:
    matchLabels:
      app: webmvc
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      containers:
      - name: webmvc
        image: warshall/webmvc:v1.0.0
        env:
        - name: IdentityUrl
          value: "http://identity-api.projet-apps.svc.cluster.local"
        - name: ApplicantsUrl
          value: "http://applicants-api.projet-apps.svc.cluster.local"
        - name: JobsUrl
          value: "http://jobs-api.projet-apps.svc.cluster.local"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "900Mi"
          limits:
            cpu: "1"
            memory: "2000Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webmvc
  namespace: projet-apps
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webmvc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webmvc-hpa
  namespace: projet-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webmvc
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60