# 1. Définition de l'identité (le compte de service)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-tester-sa
  namespace: projet-apps
---
# 2. Définition des permissions (le rôle)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: projet-apps
rules:
- apiGroups: [""]      # Groupe d'API de base
  resources: ["pods"]  # On ne donne accès qu'aux pods
  verbs: ["get", "list", "watch"] # Lecture seule
---
# 3. Lien entre l'identité et les permissions (le binding)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: projet-apps
subjects:
- kind: ServiceAccount
  name: load-tester-sa
  namespace: projet-apps
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io