apiVersion: v1
kind: Service
metadata:
  name: recrutement-app-web
  labels:
    app: webmvc
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.containerPort }}
  selector:
    app: webmvc
