apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicants-api
  namespace: projet-apps
  labels:
    app: applicants-api
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicants-api
  template:
    metadata:
      labels:
        app: applicants-api
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sql
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: applicants-api
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # Port interne de l'image Microsoft
        env:
        # --- TOUTES LES VARIABLES FUSIONNÉES ICI ---
        - name: LOGSTASH_URL
          value: "logstash:5044"
        - name: ConnectionString
          value: "Server=sql-data;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;"
        - name: HostRabbitmq
          value: "rabbitmq"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        # ------------------------------------------
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1500Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080 # Corrigé en 8080
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080 # Corrigé en 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: applicants-api
  namespace: projet-apps
spec:
  type: ClusterIP
  selector:
    app: applicants-api
  ports:
  - port: 80       # Port exposé pour les autres services (Web)
    targetPort: 8080 # Port réel vers le Pod