apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicants-api
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicants-api
  template:
    metadata:
      labels:
        app: applicants-api
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sql-data
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: applicants-api
        image: warshall/applicants-api:v1.0.0
        env:
        - name: ApiSettings__ConnectionString
          value: "Server=sql-data;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;"
        - name: ApiSettings__RedisConnectionString
          value: "redis:6379"
        # Ajout de plusieurs variantes pour garantir que le code trouve l'h√¥te
        - name: RabbitMq__Host
          value: "rabbitmq"
        - name: ApiSettings__HostRabbitmq
          value: "rabbitmq"
       
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.5"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: applicants-api
  namespace: projet-apps
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: applicants-api