apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: warshall/identity-api:v2.2.0
        imagePullPolicy: Always
        # Réduction du sleep : 60s était trop long et déclenchait les échecs des sondes
        command: ["/bin/sh", "-c"]
        args: ["sleep 60; dotnet Identity.Api.dll"]
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:80"

        # AFFINITÉ : Identity pointe vers user-data [cite: 2026-01-20]
        - name: ConnectionString
          value: "Server=user-data.ns-data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True;Connect Timeout=60;"
        - name: ApiSettings__ConnectionString
          value: "Server=user-data.ns-data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True;Connect Timeout=60;"

        - name: RedisHost
          value: "redis.ns-data.svc.cluster.local:6379"

        # RÉSEAU : FQDN complet pour joindre le namespace ns-data
        - name: RabbitMq__Host
          value: "rabbitmq.ns-data.svc.cluster.local"
        - name: ApiSettings__HostRabbitmq
          value: "rabbitmq.ns-data.svc.cluster.local"
        - name: HostRabbitmq
          value: "rabbitmq.ns-data.svc.cluster.local"

        ports:
        - containerPort: 80

        # Ajustement des sondes pour éviter les RESTARTS inutiles
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30 # Attente après le sleep 10 + boot .NET
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 90 # On laisse 1min30 avant de considérer un crash réel
          periodSeconds: 20

        resources:
          requests:
            cpu: "0.5" # Équivalent à 500m [cite: 2026-01-20]
            memory: "500Mi" # [cite: 2026-01-20]
          limits:
            cpu: "1" # [cite: 2026-01-20]
            memory: "1500Mi" # [cite: 2026-01-20]
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: identity-api