apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: warshall/identity-api:v2.3.0
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["sleep 60; dotnet identity.api.dll"]
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:80"

        # AFFINITÉ : Identity pointe vers user-data (et non sql-data)
        - name: ConnectionString
          value: "Server=user-data.ns-data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True;Connect Timeout=60;"
        - name: ApiSettings__ConnectionString
          value: "Server=user-data.ns-data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True;Connect Timeout=60;"

        - name: ApiSettings__RedisConnectionString
          value: "redis.ns-data:6379"

        # RÉSEAU : FQDN complet pour traverser les namespaces vers ns-data
        - name: RabbitMq__Host
          value: "rabbitmq.ns-data.svc.cluster.local"
        - name: ApiSettings__HostRabbitmq
          value: "rabbitmq.ns-data.svc.cluster.local"
        - name: HostRabbitmq
          value: "rabbitmq.ns-data.svc.cluster.local"

        ports:
        - containerPort: 80

        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 85 # 60s sleep + 25s boot .NET
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 130 # Marge de sécurité pour éviter le CrashLoop
          periodSeconds: 20

        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: identity-api