apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: warshall/identity-api:v2.1.0
        imagePullPolicy: Always
        # --- FIX TIMING : On attend que SQL et Redis soient prÃªts ---
        command: ["/bin/sh", "-c"]
        args: ["sleep 45; dotnet identity.api.dll"]
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ConnectionString
          value: "Server=sql-data.ns-data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True;Connect Timeout=60;"
        - name: ApiSettings__ConnectionString
          value: "Server=sql-data.ns-data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True;Connect Timeout=60;"
        
        # --- FIX NOM REDIS : Doit correspondre au Service dans ns-data ---
        - name: ApiSettings__RedisConnectionString
          value: "redis.ns-data:6379"
        
        - name: RabbitMq__Host
          value: "rabbitmq.ns-data"
        - name: ApiSettings__HostRabbitmq
          value: "rabbitmq.ns-data"
        ports:
        - containerPort: 80
        # --- FIX SONDES ---
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 50
          periodSeconds: 10
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: identity-api