apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec: # <-- L'affinité doit être ici
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sql-data
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: identity-api
        image: warshall/identity-api:v1.0.0
        env:
        - name: ApiSettings__ConnectionString
          value: "Server=sql-data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;"
        - name: ApiSettings__RedisConnectionString
          value: "redis:6379"
        - name: RabbitMq__Host
          value: "rabbitmq"
        - name: ApiSettings__HostRabbitmq
          value: "rabbitmq"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        ports:
        - containerPort: 80
        resources: # Ajout des ressources selon tes limites
          requests:
            cpu: "0.5"
            memory: "800Mi" # Augmenté à 800 pour le boot
          limits:
            cpu: "1"
            memory: "1500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: identity-api