apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["redis"]
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: identity-api
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # Port standard de l'image sample .NET
        env:
        - name: LOGSTASH_URL
          value: "logstash:5044"
        - name: RedisHost
          value: "redis:6379"  # Corrig√© : pointe vers le service redis
        - name: HostRabbitmq
          value: "rabbitmq"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests: { cpu: "500m", memory: "500Mi" }
          limits: { cpu: "1000m", memory: "1500Mi" }
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  ports: 
  - port: 80
    targetPort: 8080 # Redirige le port 80 vers le 8080 du Pod
  selector: 
    app: identity-api