apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: warshall/identity-api:v1.0.0
        env:
        - name: ApiSettings__ConnectionString
          value: "Server=sql-data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;"
        - name: ApiSettings__RedisConnectionString
          value: "redis:6379"
        - name: ApiSettings__HostRabbitmq
          value: "rabbitmq"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: projet-apps
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: identity-api


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: identity-api
#   namespace: projet-apps
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: identity-api
#   template:
#     metadata:
#       labels:
#         app: identity-api
#     spec:
#       containers:
#       - name: identity-api
#         image: warshall/identity-api:v1.0.0
#         env:
#         - name: ConnectionString
#           value: "redis:6379"
#         - name: RedisConnectionString
#           value: "redis:6379"
#         - name: ConnectionStringDatabase
#           value: "Server=sql-data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;"
#         - name: HostRabbitmq
#           value: "rabbitmq"
#         - name: ASPNETCORE_URLS
#           value: "http://+:8080"
#         ports:
#         - containerPort: 80
#         livenessProbe:
#           httpGet:
#             path: /hc
#             port: 80
#           initialDelaySeconds: 120
#         readinessProbe:
#           httpGet:
#             path: /hc
#             port: 80
#           initialDelaySeconds: 60
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: identity-api
#   namespace: projet-apps
# spec:
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: identity-api