apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-data
  namespace: projet-apps
spec:
  serviceName: sql-data
  replicas: 1
  selector:
    matchLabels:
      app: sql-data
  template:
    metadata:
      labels:
        app: sql-data
    spec:
      # --- OPTIMISATION ARCHITECTE ---
      # Empêche de mettre deux instances SQL sur le même nœud si vous scalez
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sql-data
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: sql-data
          image: warshall/sql-data:v2.0.0 
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Pass@word"
          # --- RESSOURCES MISES À JOUR ---
          resources: 
            requests:
              cpu: "500m"
              memory: "1500Mi"
            limits:
              cpu: "1000m"
              memory: "2000Mi" 
          volumeMounts:
            - name: sql-storage
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: sql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sql-data
  namespace: projet-apps
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: sql-data
