apiVersion: v1
kind: Service
metadata:
  name: sql.data # Nom crucial pour que les APIs trouvent la DB
spec:
  type: ClusterIP
  selector:
    app: sql
  ports:
    - port: 1433
      targetPort: 1433