apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-data
  namespace: ns-data
spec:
  serviceName: user-data
  replicas: 1
  selector:
    matchLabels:
      app: user-data
  template:
    metadata:
      labels:
        app: user-data
    spec:
      containers:
      - name: user-data
        image: mcr.microsoft.com/mssql/server:2019-latest 
        imagePullPolicy: Always
        # --- AJOUT CRUCIAL ICI ---
        securityContext:
          runAsUser: 0
        # ------------------------
        ports:
        - containerPort: 1433
          name: sql-port
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Pass@word123!"
        - name: MSSQL_TCP_PORT
          value: "1433"
        
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 30
          periodSeconds: 10

        resources:
          requests:
            cpu: "250m"
            memory: "700Mi" 
          limits:
            cpu: "1"
            memory: "1500Mi"
            
        volumeMounts:
        - name: user-storage
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: user-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: user-data
  namespace: ns-data
spec:
  type: ClusterIP
  ports:
  - port: 1433
    targetPort: 1433
    name: sql-port
  selector:
    app: user-data